# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ninth and O Youth Ministry
email: paulrcook@me.com
description: > # this means to ignore newlines until "baseurl:" This is the blog for the Ninth and O Youth Ministry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://naobcyouth.org" # the base hostname & protocol for your site
github_username: cookavich
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"

# Build settings
sudomarkdown: kramdown
